apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: shitcoin
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shitcoin
      component: frontend
  template:
    metadata:
      labels:
        app: shitcoin
        component: frontend
    spec:
      containers:
        - name: frontend
          image: shitcoin-frontend
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
